[package]

name = "gl"
version = "0.0.1"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>",
        "Corey Richardson",
        "Arseny Kapoulkine"
]

build = "./.build.sh"

[[lib]]

name = "gl"
