[package]

name = "gl"
version = "0.0.2-pre"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>",
        "Corey Richardson",
        "Arseny Kapoulkine"
]
description = "Bindings for the latest core version of OpenGL."
repository = "https://github.com/bjz/gl-rs"
keywords = ["opengl"]
readme = "README.md"
license = "Apache-2.0"

[lib]
name = "gl"
path = "src/gl/lib.rs"

[dependencies.gl_generator]
path = "src/gl_generator"
version = "*"

[dev-dependencies]
glfw = "*"
