[package]
name = "gl_common"
version = "0.0.3-pre"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
repository = "https://github.com/bjz/gl-rs"
keywords = ["opengl"]
license = "Apache-2.0"
