[package]
# we don't include some metadata to avoid accidental publishes
name = "gl_tests"
version = "0.0.1"
build = "build.rs"

[build-dependencies]
khronos_api = "1.0.0"

[build-dependencies.gl_generator]
path = "../gl_generator"
version = "0.4.0"
